### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by jakoch** [jakoch/cpuinfo_cmake#1]
- [x] escape script for cpuinfo.cpp -> output cpuinfo.cmake
- [x] test project
   - [x] setup test/cmake and test/src 
   - [x] copy generated cpuinfo.cmake into test/cmake
   - [x] cmakelists.txt include(cpuinfo.cmake)
   - [x] build a hello world app with a "hellow from conditional feature"
 - [x] CPUINFO.cmake is escaped and included, successfully compiled, 
      - [x] but cpuinfo.json is not written .. find out why
      - seems cpuinfo.json was written, but to an unknown location.. maybe cmake working dir
      - [x] solved by writing the file to the CMAKE_BINARY_DIR, else it gets lost somewhere...
